### ISSUE TITLE
Crashing bug: assertion failed: is_special(ctrl)

### ISSUE THREAD

**Issue by badboy** [Amanieu/hashbrown#1]
First: thanks for your talk last night, very enjoyable!

This morning I tried using this new hashmap implementation in my own code as a replacement for libstd's HashMap.

The following code leads to a crash (extracted from my own code and minimized):

```rust
extern crate hashbrown;

use hashbrown::HashMap;

fn main() {
    let mut htab = HashMap::new();
    htab.insert(51419, 3);
    htab.insert(32640, 9);
    htab.insert(32475, 22);
}
``` 

Error output:

```
   Compiling hashbrown-bug v0.1.0 (/Users/jrediger/projects/rust/hashbrown-bug)
    Finished dev [unoptimized + debuginfo] target(s) in 0.96s
     Running `target/debug/hashbrown-bug`
thread 'main' panicked at 'assertion failed: is_special(ctrl)', /Users/jrediger/.cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.1.0/src/raw/mod.rs:62:5
stack backtrace:
   0:        0x109f0caff - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hd303b0cd45bccf60
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:        0x109f0497d - std::sys_common::backtrace::print::hf2fe31942821bdcb
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:        0x109f0e543 - std::panicking::default_hook::{{closure}}::h748cb38cc840cba6
                               at libstd/panicking.rs:211
   3:        0x109f0e2cc - std::panicking::default_hook::h81d2ef89c2ad110e
                               at libstd/panicking.rs:227
   4:        0x109f0ebb7 - <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get::hc265418ddf96c674
                               at libstd/panicking.rs:477
   5:        0x109f0e71c - std::panicking::continue_panic_fmt::h2d9dbf1e069d262d
                               at libstd/panicking.rs:391
   6:        0x109f0e608 - std::panicking::try::do_call::hcfe6ac53944e0624
                               at libstd/panicking.rs:326
   7:        0x109f47931 - core::ptr::drop_in_place::h2136aea44990720c
                               at libcore/panicking.rs:77
   8:        0x109f47866 - core::ptr::drop_in_place::h2136aea44990720c
                               at libcore/panicking.rs:52
   9:        0x109f01020 - hashbrown::raw::special_is_empty::hd3788a278ef6424a
                               at /Users/jrediger/projects/rust/hashbrown-bug/<::core::macros::panic macros>:3
  10:        0x109efe68e - <hashbrown::raw::RawTable<T>>::insert::h3b2c729d59f9a98d
                               at /Users/jrediger/.cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.1.0/src/raw/mod.rs:614
  11:        0x109eff8a2 - <hashbrown::map::HashMap<K, V, S>>::insert::h8ea3dcf9ba9cb1e3
                               at /Users/jrediger/.cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.1.0/src/map.rs:789
  12:        0x109f01571 - hashbrown_bug::main::h8e60525e2e5179d7
                               at src/main.rs:9
  13:        0x109f001e1 - std::rt::lang_start::{{closure}}::hc81fccad58df1a5d
                               at libstd/rt.rs:74
  14:        0x109f0e5e7 - std::panicking::try::do_call::hcfe6ac53944e0624
                               at libstd/rt.rs:59
                               at libstd/panicking.rs:310
  15:        0x109f1ad6e - macho_symbol_search
                               at libpanic_unwind/lib.rs:103
  16:        0x109f0a49c - std::sys_common::bytestring::debug_fmt_bytestring::h2a45b81d7d291ba2
                               at libstd/panicking.rs:289
                               at libstd/panic.rs:392
                               at libstd/rt.rs:58
  17:        0x109f001c1 - std::rt::lang_start::h0cd91951811e88d1
                               at libstd/rt.rs:74
  18:        0x109f015c1 - hashbrown_bug::main::h8e60525e2e5179d7
```

Hardware: MacBook Pro running macOS High Sierra 10.13.6 on an Intel Core i7

**Comment by Amanieu** [comment]
Yikes, it seems that you hit an edge case that only occurs with small tables (< 16 buckets). I am working on fix for this.

**Comment by cuviper** [comment]
If you'd like another test case, I encountered the same assertion with the following input:

```rust
extern crate hashbrown;

use hashbrown::HashSet;

fn main() {
    let x: Vec<u16> = vec![23, 51, 23, 51, 7, 35];
    let y: Vec<u16> = vec![97, 69, 99, 71, 113, 85];
    let _: HashSet<_> = x.into_iter().zip(y).collect();
}
```

It does work with git master though, so I look forward to a published update to the crate!

**Comment by Amanieu** [comment]
I just publish 0.1.1

**Comment by badboy** [comment]
Thanks! My code now works.
